spring:
  thymeleaf:
    enabled: false
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/test1
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      prefix: /
      suffix: .jsp

server:
  port: 8080
  servlet:
    context-path: /

